### ISSUE TITLE
Bug when running tool

### ISSUE THREAD

**Issue by djunGD** [shtyler/datagenerator#6]
When running the data gen tool through SQL Executor, I encountered the following error:

`2021-03-11T22:31:58.947+0100 [Ruby-0-Thread-1: /mnt/execution/lib/gdc_etl_sql_executor.rb:150] /mnt/execution/vendor/bundle/jruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/jdbc.rb:215: warning: constant ::NativeException is deprecated
2021-03-11T22:32:00.326+0100 [Ruby-0-Thread-1: /mnt/execution/lib/gdc_etl_sql_executor.rb:150] /mnt/execution/vendor/bundle/jruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/jdbc.rb:692: warning: constant ::NativeException is deprecated
2021-03-11T22:32:00.347+0100 [Ruby-0-Thread-1] [ERROR]: [#7] Thread has finished with error: The execution of file 01_run_datagen.sql has failed. Message Java::JavaSql::SQLException: Functions 'randomfact, randomcustomdata, randomdata, randomdate' do not exist. ["/mnt/execution/lib/gdc_etl_sql_executor/work_units/work_unit_sql.rb:26:in `block in work'", "/mnt/execution/lib/gdc_etl_sql_executor/helpers/condition_helper.rb:31:in `condition'", "/mnt/execution/lib/gdc_etl_sql_executor/work_units/work_unit_sql.rb:13:in `work'", "/mnt/execution/lib/gdc_etl_sql_executor/work_factory.rb:20:in `work'", "/mnt/execution/lib/gdc_etl_sql_executor.rb:157:in `block in spawn_worker_thread'"]
2021-03-11T22:32:02.147+0100 [main] StandardError: Some of the SQL commands has failed. Error scripts: ["01_run_datagen.sql"]
   run_workers at /mnt/execution/lib/gdc_etl_sql_executor.rb:145
  execute_sqls at /mnt/execution/lib/gdc_etl_sql_executor.rb:111
          call at /mnt/execution/lib/execute_brick.rb:25
        <main> at /mnt/execution/main.rb:23
2021-03-11T22:32:02.148+0100 [main] [ERROR]: action=jvmscript script=main.rb status=SCRIPT_ERROR
The execution finished with error`

I think it's a result of the 3rd Liquid template not having the Date, Data, and Fact functions from the 2nd template

**Comment by shtyler** [comment]
Functions creation put to a separate script that runs prior to datagen.
